### ISSUE TITLE
Ideas for structuring the workshop

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron-workshop/potentials-workshop-2021#1]
Some ideas for the workshop from our weekly developer meeting. Please feel free to modify/add to this in this discussion

## Day 1

- Introduction to pyiron (simple calculations)
- Workflow for Free energy calculations
- Show how to construct structure data for fitting

## Day 2

- Running the various potential fitting codes 

## Day 3

- Looping over the generated potentials from day 2 to calculate free energies from the workflows shown in day 1

**Comment by jan-janssen** [comment]
@sudarsan-surendralal I guess we can close this now
