### ISSUE TITLE
Login Instructions 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron-workshop/potentials-workshop-2021#19]
@muh-hassani I guess it makes sense to add some instructions on how to login on: 
https://pyiron-workshop.ml 

In addition I got the following message during my first login which was a bit confusing: 
<img width="511" alt="Screenshot 2021-03-03 at 10 37 21" src="https://user-images.githubusercontent.com/3854739/109786016-05e14300-7c0d-11eb-880c-33c2c19cfe8c.png">

**Comment by max-hassani** [comment]
> @muh-hassani I guess it makes sense to add some instructions on how to login on:
> https://pyiron-workshop.ml

Sure, I will add some instructions for the login. I will also remove this additional step for the consent of the users. 
I have created a list of the passwords for all the participants. But I guess the email should be sent from the organizer's email address, and not mine.

**Comment by max-hassani** [comment]
@jan-janssen, Shall the created one-time passwords and usernames be included in the same google spreadsheet?

**Comment by jan-janssen** [comment]
> @jan-janssen, Shall the created one-time passwords and usernames be included in the same google spreadsheet?

yes, that should be fine - @yury-lysogorskiy is going to include them in the email send to the participants.

**Comment by jan-janssen** [comment]
![warning](https://user-images.githubusercontent.com/3854739/109831155-76a15300-7c3f-11eb-8933-cb15449074c7.png)
