### ISSUE TITLE
Atomicrex use structure container 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron-workshop/potentials-workshop-2021#6]
@Leimeroth I noticed that you are currently importing the atomistic structures from Yury's pickle file rather than using the updated structure container Marvin developed. Can you update your notebook? Here is an example of using the structure container with atomicrex https://github.com/jan-janssen/pyiron-atomicrex

**Comment by Leimeroth** [comment]
Thanks for the example. I will change the notebook accordingly tomorrow. Also will include a much better fit of the 1000 structure data set.

**Comment by Leimeroth** [comment]
Done
