### ISSUE TITLE
Workflow-RuNNer.ipynb needs update

### ISSUE THREAD

**Issue by max-hassani** [pyiron-workshop/potentials-workshop-2021#66]
in the `Workflow-RuNNer.ipynb`, from day2, the following tries to unpack the dataset from some tar archieve file:
```
data_pr = Project("../../datasets")
if len(data_pr.job_table()) == 0:
    data_pr.unpack("Cu_training_archive")
```
But we have already imported these data on the start of the docker container, and there is no `Cu_training_archive` in the `datasets` directory. I believe it should be replaced by the following:
```
data_pr = Project("../../datasets")
#if len(data_pr.job_table()) == 0:
#    data_pr.unpack("Cu_training_archive")
```
@jan-janssen , and @mrshrbld, am I right?

**Comment by jan-janssen** [comment]
No the if statement is false so the unpack is not executed

**Comment by max-hassani** [comment]
@jan-janssen, you are right, my mistake. Sorry!
