### ISSUE TITLE
central structure database 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron-workshop/potentials-workshop-2021#7]
Currently each notebook for day 2 and day 3 imports the structure database in a slightly different way. It would be nice if we could all agree on a central location where to place the structure database and then load it. @Leimeroth @yury-lysogorskiy @sudarsan-surendralal

**Comment by Leimeroth** [comment]
Suggest a location and I will try to use it when I change the notebook to use marvins container. Shouldn't cause any problems I guess.

**Comment by yury-lysogorskiy** [comment]
The same for me, just suggest the location for
```
data_pr = Project("import_database")
```
and I will load it from there

**Comment by sudarsan-surendralal** [comment]
I agree with @yury-lysogorskiy. Something like `data_pr = Project("<location of the dataset projects on the cloud>")` should be fine. It's just that we should make this project is read-only so that a participant won't accidentally delete it.

**Comment by pmrv** [comment]
I used the location from @sudarsan-surendralal  [PR](https://github.com/pyiron/pyiron_potentialfit/pull/21) now, which is 
```python
pr = pyiron.Project(\"imported_datasets\")
```
if I see this correctly.

**Comment by jan-janssen** [comment]
I did this in https://github.com/pyiron/pyiron_potentialfit/pull/39 @muh-hassani Can you execute the `postBuild` script https://github.com/pyiron/pyiron_potentialfit/blob/master/binder/postBuild before the user logs in the first time? This imports the dataset and writes the database `pyiron.db` to the users home directory.

**Comment by max-hassani** [comment]
> I did this in https://github.com/pyiron/pyiron_potentialfit/pull/39 @muh-hassani Can you execute the `postBuild` script https://github.com/pyiron/pyiron_potentialfit/blob/master/binder/postBuild before the user logs in the first time? This imports the dataset and writes the database `pyiron.db` to the users home directory. 

I will add this to the postscript, but this will be repeated every time the user logs in. Doesn't this cause a problem?

**Comment by jan-janssen** [comment]
Maybe you can check if the `pyiron.db` file already exists in the home directory and only execute the rest when it does not/

**Comment by max-hassani** [comment]
> 
> 
> Maybe you can check if the `pyiron.db` file already exists in the home directory and only execute the rest when it does not/

It is a good solution. But the users who till now have already performed some jobs and have `pyiron.db` created in their home directory, have to import the database/jobs via unpack method by themselves.

**Comment by jan-janssen** [comment]
I guess we should anyway reset the permanent storage before the workshop - let's discuss this tomorrow.

**Comment by Leimeroth** [comment]
I wanted to run the atomicrex notebook and noticed that this
```
if len(data_pr.job_table()) == 0:
    data_pr.unpack("../../datasets/Cu_training_archive")
throws a file not found error. I think it is related to the relative filepath because it says
FileNotFoundError: [Errno 2] No such file or directory: 'Cu_training_archive.tar.gz'
```
and the ImportDatabase notebook in the datasets directory works fine

**Comment by jan-janssen** [comment]
> I wanted to run the atomicrex notebook and noticed that this

Locally or on `workshop.pyiron.org` ? And how is the `data_pr` defined, in the latest notebook it is: 
```
data_pr = Project("../../datasets")
```
https://github.com/pyiron/pyiron_potentialfit/blob/master/day_2/atomicrex/WorkshopPotentialEAM.ipynb

**Comment by Leimeroth** [comment]
locally, and data_pr = Project("../../datasets")
As workaround I ran the ImportDatabase notebook and used data_pr = Project("../../datasets/imported_datasets/"), which works fine.

**Comment by Leimeroth** [comment]
Also fails in #48
