### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron-workshop/potentials-workshop-2021#8]
@sudarsan-surendralal Can you update the installation instructions? 

The environment can now be installed via conda: 
```
conda env update --file binder/environment.yml
```

In addition for the moment the users also have to install `pyiron_contrib` and `pyiron_gpl` from specific branches as shown here: 
https://github.com/pyiron/pyiron_potentialfit/blob/master/binder/postBuild

**Comment by sudarsan-surendralal** [comment]
Should I update the `environment.yml` file instead? Also, we're going to merge these branches of `pyiron_contrib` and `pyiron_gpl` before the workshop right?

**Comment by jan-janssen** [comment]
I just updated both packages - so once they are available we can update the environment file.
